puyepuye/207-project-soulsync

- README.md
> Chuyian in your area.

- README.md
> chore add name to contributor

- README.md
> chore: try pr temp

- README.md
I added my name to README pls be proud
> chore: add my name to README

- README.md
> chore add Yoli

- README.md
> chore add Mac's name

- README.md
- src/main/java/app/LoginUseCaseFactory.java
- src/main/java/app/MainWithDB.java
- src/main/java/app/MainWithInMemory.java
- src/main/java/interface_adapter/login/LoginController.java
- src/main/java/interface_adapter/login/LoginPresenter.java
- src/main/java/use_case/login/LoginInputBoundary.java
- src/main/java/use_case/login/LoginInteractor.java
- src/main/java/use_case/login/LoginOutputBoundary.java
- src/main/java/view/LoginView.java
- src/test/java/use_case/login/LoginInteractorTest.java
> feature: login to signup flow

- src/main/java/data_access/DBUserDataAccessObject.java
- src/main/java/data_access/FileUserDataAccessObject.java
- src/main/java/data_access/InMemoryUserDataAccessObject.java
- src/main/java/data_access/MongoDB.java
- Created MongoDB class to merge MongoDB & DBUserDataAccessObject classes.
- DBUserDataAccessObject class integrates w/ MongoDB.
> Connected to MongoDB

- src/main/java/data_access/SendBirdChatObject.java
> added a SendBird API data access object

- src/main/java/data_access/SendBirdChatObject.java
> Fixed main method for testing

- TODO.md
> chore: added new tasks

- TODO.md
- src/main/java/app/LoginUseCaseFactory.java
- src/main/java/app/MainWithDB.java
- src/main/java/app/MainWithInMemory.java
- src/main/java/data_access/DBUserDataAccessObject.java
- src/main/java/interface_adapter/login/LoginPresenter.java
- src/main/java/interface_adapter/signup/SignupController.java
- src/main/java/interface_adapter/signup/SignupPresenter.java
- src/main/java/interface_adapter/signup/SignupState.java
- src/main/java/interface_adapter/signup/SignupViewModel.java
- src/main/java/interface_adapter/swipe/SwipeState.java
- src/main/java/use_case/signup/SignupInputBoundary.java
- src/main/java/use_case/signup/SignupInputData.java
- src/main/java/use_case/signup/SignupInteractor.java
- src/main/java/view/LabelDropdownPanel.java
- src/main/java/view/LoginView.java
- src/main/java/view/SignupView.java
> feature: Connect Login to Swipe and Finished Sign up (including updating database)

- src/main/java/data_access/DBMatchesDataAccessObject.java
- src/main/java/entity/CommonMatches.java
- src/main/java/entity/CommonMatchesFactory.java
- src/main/java/entity/MatchesFactory.java
feat: added Matches interface to connect with MongoDB
> chore added Matches interface to connect with MongoDB

- src/main/java/view/ImagePanel.java
- src/main/java/view/LoginView.java
- src/main/java/view/PreferenceView.java
- src/main/java/view/ProfilePopup.java
Added ProfilePopup and ImagePanel.
To run popup, run showProfileDialog(String image, String fullName, String location, String gender, Date dateOfBirth, String bio, List<String> tags).
Popup page is not connected to other files currently.
> feat: added profile popup page

- src/main/java/interface_adapter/preferences/PreferencesPresenter.java
- src/main/java/view/SignupView.java
> bug-fix: show swipe functionality

- TODO.md
- src/main/java/interface_adapter/compatibility/CompatibilityController.java
- src/main/java/interface_adapter/preferences/PreferencesPresenter.java
- src/main/java/use_case/compatibility/CompatibilityCalculator.java
- src/main/java/use_case/compatibility/CompatibilityInputBoundary.java
- src/main/java/use_case/compatibility/CompatibilityInteractor.java
- src/main/java/use_case/compatibility/FengshuiCalculator.java
- src/main/java/use_case/swipe/SwipeInputBoundary.java
- src/main/java/use_case/swipe/SwipeUserDataAccessInterface.java
- src/main/java/view/CompatibilityView.java
- src/main/java/view/SwipeView.java
> bug-fix: fix return compatibility calculator etc.

- .env
- pom.xml
- src/main/java/view/ProfileUploadView.java
Add Dependency file. 
rm -- env file from tracking.
> Dependency for Cloudinary

- src/main/java/data_access/DBUserDataAccessObject.java
> [bugfix] login hashmap

- src/main/java/view/ProfileUploadView.java
- src/main/java/view/SignupView.java
Updated sign up ui to meet colour theme and added labels to some input choices.
> Updated Sign Up UI

- src/main/java/app/MainWithDB.java
- src/main/java/view/EditProfileView.java
Updated format of edit profile view
> Formatted edit profile view

- src/main/java/use_case/change_password/ChangePasswordInputData.java
- src/test/java/use_case/changePassword/ChangePasswordInteractorTest.java
feature added test case for ChangePasswordInteractorTest.java
> feature added test case for ChangePasswordInteractorTest.java

- src/main/java/interface_adapter/preferences/PreferencesPresenter.java
- src/main/java/view/SwipeView.java
> fix: fix generating swiped after sign up

- src/main/java/app/ChatUseCaseFactory.java
- src/main/java/app/CompatibilityUseCaseFactory.java
- src/main/java/app/EditProfileUseCaseFactory.java
- src/main/java/app/ListChatUseCaseFactory.java
- src/main/java/app/LoginUseCaseFactory.java
- src/main/java/use_case/swipe/SwipeOutputData.java
- src/test/java/use_case/swipe/SwipeInteractorTest.java
> feat: Added full coverage test cases for SwipeInteractor

- src/test/java/use_case/compatibility/CompatibilityInteractorTest.java
- src/test/java/use_case/edit_profile/EditProfileInteractorTest.java
- src/test/java/use_case/preferences/PreferenceInteractorTest.java
> add one test case

- src/main/java/app/MainWithDB.java
- src/main/java/app/MainWithInMemory.java
- src/main/java/app/NavbarUseCaseFactory.java
- src/main/java/app/PreferenceUseCaseFactory.java
- src/main/java/app/SignupUseCaseFactory.java
- src/main/java/app/SwipeUseCaseFactory.java
- src/main/java/data_access/cloudinary/CloudinaryUploader.java
- src/main/java/view/ProfileUploadView.java
- src/test/java/entity/EntityTests.java
> Jaroonje fixbug

- src/test/java/use_case/swipe/SwipeInteractorTest.java
Since the parameters of SwipeInteractor was changed, the test has to be updated accordingly.
> fix: SwipeInteractorTest

- src/main/java/app/PreferenceUseCaseFactory.java
- src/main/java/entity/ChatChannel.java
- src/main/java/entity/ChatMessage.java
- src/main/java/view/ChatView.java
- src/main/java/view/ListChatView.java
- src/test/java/use_case/chat/ChatInteractorTest.java
Added import statement to PreferencesViewModel to PreferencesUseCaseFactory.
Change getChatUrl, setChatUrl, and getChannelUrl to getChatURL, setChatURL, and getChannelURL.
> fix: changed getUrl to getURL

- src/main/java/use_case/login/LoginUserDataAccessInterface.java
- src/main/java/use_case/signup/SignupInputData.java
- src/test/java/use_case/login/LoginInteractorTest.java
- src/test/java/use_case/signup/SignupInteractorTest.java
chore cleaned unused implementations
> chore cleaned unused implementations

- src/main/java/use_case/login/LoginInteractor.java
- src/test/java/use_case/login/LoginInteractorTest.java
> removed unused import

- src/test/java/use_case/signup/SignupInteractorTest.java
chore changed ordering of test cases for readability
> chore changed ordering of test cases for readability

- src/test/java/use_case/login/LoginInteractorTest.java
chore more changes of ordering of test cases for readability
> chore more changes of ordering of test cases for readability
